name: ddd
description: "tools and abstractions for implementing Domain-Driven Design principles in Dart applications."
version: 0.0.2

homepage: https://github.com/Sedrakyan-AM/ddd

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

dev_dependencies:

flutter:
